version: '3.4'

services:
  cloudlabbclient:
    image: micaelmoon/cloudlabbclient
    build:
      context: ./CloudLabbClient
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    networks:
     - cloudlabbnetwork

  terraformlabbapi:
    image: micaelmoon/terraformlabbapi:latest
    ports:
     - "8081:8081"
    depends_on:
     - sqlserver
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:8081
    networks:
     - cloudlabbnetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password12345!"
      ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"
    volumes:
     - sqlvolume:/var/opt/mssql
    networks:
     - cloudlabbnetwork

networks:
  cloudlabbnetwork:

volumes:
  sqlvolume: